### ISSUE TITLE
InternationalDay のチェックリスト

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/osaka#11]
土曜日のために色んなタスクがありますので、ちょっとここにまとめようと思います

- [ ] 飲み会のレストラン選ぶ #10  (@atuyl)
- [x] 飲み会のイベントをDoorkeeperにつける (@atuyl)
- [x] 21日（木曜日）にリマインダーを出す (@kamiyam)
- [ ] 参加者リストを印刷する (@kamiyam)
- [x] ステッカーを注文する (@martinheidegger)
- [x] アクセスの動画 (@martinheidegger + @AtuyL)
- [ ] 1人300¥の食べ物・飲み物を用意する (@kamiyam)
- [ ] Doorkeeperのサイトに発表のテーマを乗せる
- [ ] データー管理(@kumatch)
- [ ] 当日写真撮る人
- [ ] 発表者検索
- [ ] 動画を撮る準備 https://github.com/nodeschool/international-day/issues/9#issuecomment-103419270
- [ ] 当日のお金他当社
- [ ] 当日の入口

手伝い人をて上げてください！

**Comment by kamiyam** [comment]
・21日（木曜日）にリマインダーを出す
・参加者リストを印刷する
・1人300¥の食べ物・飲み物を用意する
やりましょうか？

**Comment by martinheidegger** [comment]
食べ物・飲み物は何を考えていますか？

**Comment by martinheidegger** [comment]
(あなたを担当者としてつけました）

**Comment by kamiyam** [comment]
okay！

「食べ物・飲み物」は会場に置く お飲み物・菓子ですよね？

**Comment by martinheidegger** [comment]
(水+お茶)は 20L ~ 25L ぐらいは必要
しょっぱいの食べ物は飲みたくなるからあんまりよくないかな〜と考えています。
やすい量が多いのがいいかも？

**Comment by AtuyL** [comment]
懇親会の用意なのですが、人数が多いと飲み放題以外計算が難しいので、1人2000円くらいで見繕っててもいいでしょうか？

**Comment by martinheidegger** [comment]
2000円は問題ないと思います。

**Comment by AtuyL** [comment]
Node.js勉強会 国際イベント 大阪
https://nodeschool.doorkeeper.jp/events/23614
のタイムスケジュールに、懇親会への誘導を入れました。
↓
https://nodeschool.doorkeeper.jp/events/25518

**Comment by kamiyam** [comment]
最初に聞けばよかった。すいません。
会場（VisLab Osaka）は、飲食OKでしたっけ？
それとも軽食(light meal?)ぐらいならOK？

飲食=> ピザ、寿司、ビール（例）
軽食=>お菓子、パンとか？

**Comment by martinheidegger** [comment]
飲食 OK です(あとでちゃんと片付ければ）
会議室が汚れるとよくないのでできれば コーラー、ビールは用意しないほうがいい

**Comment by yamamanx** [comment]
午前中しか参加出来なくて申し込んでおりましたが、今現在キャンセル待ちの方が6名おられたので、一度キャンセルさせていただきました。昨日のうちに確認しておけばよかったですね。遅くなりましてすいません。本日の様子はアップいただけると幸いです。また、お願いします。皆様楽しんでください！

**Comment by martinheidegger** [comment]
@yamamanx 連絡ありがとうございました、楽しかったです！
