### ISSUE TITLE
Workshop　learn-generators の日本語翻訳

### ISSUE THREAD

**Issue by kunichan2013** [nodeschool/osaka#13]
１２／１７のMartinの説明を参考にして翻訳に適したWorkshopを探しました。
https://github.com/isRuslan/learn-generators
はi18nフォルダもあり複数言語に翻訳されているのでこれに日本語を追加しようと思います。
https://github.com/kunichan2013/learn-generators
にForkしてこれからClone & Branchを作って作業していきます。

どこにお知らせすればいいのか考えましたが、ひとまずここのissuesにしました。

刀祢　(kunichan2013)

**Comment by kunichan2013** [comment]
https://github.com/isRuslan/learn-generators/tree/master/i18n
にあるように日本語訳をマージしてもらいました。

**Comment by martinheidegger** [comment]
おめでとうございます！
