### ISSUE TITLE
木 2016/06/16 日の NodeSchool

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/osaka#15]
- [x] ~~場所は？~~ FirstServer
- [x] Doorkeeper のイベント https://nodeschool.doorkeeper.jp/events/46836
- [x] Doorkeeper のメッセージ
- [x] NodeSchool ホームページに追加する

**Comment by cyan-haru-25** [comment]
2016/06/16(木)が正しいですね！
リストに上がっているのはTODOですよね？
とりあえず下３つやりましょうか？
あと、難しいかもしれませんが、場所も探してみますよ？

**Comment by martinheidegger** [comment]
場所についてですが、FirstServer の @vanx2 さんからの確認を待っていますが FirstServer になりそうです。

**Comment by cyan-haru-25** [comment]
了解しました(^－' )b

**Comment by vanx2** [comment]
すみません、Firstserverの会議室ですが16日は19時まで予定が入っていました。
19時からで大丈夫ですか？

**Comment by martinheidegger** [comment]
それなら 19:30 からスタートですよね。今日はもう 7 日だから今回例外にしましょう。 19時からは大丈夫です！

**Comment by vanx2** [comment]
あ、まだ正確には言えないけど、19時開始でOKだと思う。
会議自体は18:30に終わって、それから片付けとテーブル並べるのと電源タップの準備してぎりぎり19時スタートいけそう。

**Comment by vanx2** [comment]
開場は19:45で。まだテーブルセッティング中かもだけど。

**Comment by kumatch** [comment]
@vanx2 18:45 の typo ?

**Comment by martinheidegger** [comment]
Typoだと思うようにDoorkeeperのイベントページを用意します。

**Comment by martinheidegger** [comment]
イベントはこちらです: https://nodeschool.doorkeeper.jp/events/46836 ←@vanx2  同意お願いできますか？

**Comment by vanx2** [comment]
タイポです！
会場がロックオンになっていたので修正して公開してメッセージ送っておきました。

**Comment by vanx2** [comment]
Nodeschoolイベント追加した。

編集用URL：
https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform?edit2=2_ABaOnucgmJl2CLcAsXWQYqvrpMPC-AyAcqqKnyF-ZqYeWdWE_Ck3YMYWR0NYzQ

**Comment by martinheidegger** [comment]
ということは 19:30 からスタートですね。今日はもう 7日だから今回例外にしましょう。19時大丈夫です！
