### ISSUE TITLE
2016/7 土2 10~14  NodeSchool 大阪

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/osaka#18]
- [x] 場所 
- [x] Doorkeeper のイベント
- [x] Doorkeeper のメッセージ
- [x] NodeSchool ホームページに追加する

**Comment by cyan-haru-25** [comment]
場所：株式会社シェアウィズ
日時：2016-07-02（土）10:00 - 13:00
Doorkeeper のイベント：作成中 
　　[https://nodeschool.doorkeeper.jp/events/47197](https://nodeschool.doorkeeper.jp/events/47197)

**Comment by martinheidegger** [comment]
英語の版つけました。今回どうして土曜日にやっているのを説明が必要になりました。「これからはたまに普通のNodeSchoolの足した上に第一の土曜日にNodeSchoolを頑張りたいです。」とか

**Comment by martinheidegger** [comment]
お問い合わせありがとうございます。
今回は会場のスペースに余裕があるので、先に参加登録をして頂いて問題ありません。
もし、参加が難しくなった時点でキャンセル処理して頂ければと思います。
事前にご連絡頂いていますので、今回直前にキャンセルの手続きを行ったとしても、特にペナルティとなるようなことはありません。
今回が参加できない場合は 7/2にもイベントを用意中です。
https://github.com/nodeschool/osaka/issues/18#issuecomment-225756048

よろしくお願いします。
ハイデッガー マルティン

**Comment by cyan-haru-25** [comment]
とりあえず以下の文章を入れましたm(_ _)m
英語版は、、対応して頂けると、、、嬉しい( ´Д｀)

---

## 今回の開催について

これまでは通常 `第３木曜日` に行ってきましたが、平日はなかなか参加できないというご意見を受け、現在`第１土曜日`の実施も検討しています。  
開催頻度や内容は会のフィードバックを受けて決めていきたいと考えています。

今回はその第１回目となります！

---

あと、未確定箇所は[調整中](adjusting now) 等にしておきました。
いつでも公開できます。

送る`メッセージ`は下のを入れて送るで良いかと思っています！
どうでしょう！？　問題なければ送って公開します！

--------------------------------------------------------------------

「休日の開催です。
平日の参加が難しい方はこの機会に是非！」

**Comment by martinheidegger** [comment]
翻訳しました。
メッセージはこちらです。
https://manage.doorkeeper.jp/groups/nodeschool/events/47197/notifications/38550/edit
公開お願いします。

**Comment by martinheidegger** [comment]
公開ありがとうございました。NodeSchoolのHPに追加してください: https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform?usp=form_confirm

**Comment by cyan-haru-25** [comment]
登録しました、が、日本語で登録しちゃいました^^;
直し方が分からないので、とりあえずこれで∑(ﾟ◇ﾟ；)
