### ISSUE TITLE
International NodeBots Day

### ISSUE THREAD

**Issue by yoshidaken1** [nodeschool/osaka#20]
あまり参加していない吉田研一です。
7/30（土）にInternational NodeBots Dayというものがあり、大阪でもできないかと思っているのですが、みなさんいかがでしょうか？
http://nodebots.io/

ワークショップ： https://github.com/tableflip/nodebot-workshop
みんなでLED blinkができる程度ができればいいなと考えています。

**Comment by martinheidegger** [comment]
いいですね！残念ながら私はその時に海外にいますので、別のオーガナイザーがいると思います。

**Comment by cyan-haru-25** [comment]
ごめんなさい、、不参加の予定です( ´Д｀)
