### ISSUE TITLE
特別のイベント： NodeSchool のインタナショナルの日

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/osaka#8]
http://nodeschool.io/international-day/ のためには大阪も登録しました。会議場を探しています。

@nodeschool/osaka メンバーはその日発表したいですか？

**Comment by kamiyam** [comment]
@martinheidegger これは何時に開催で何をする日ですか？

**Comment by martinheidegger** [comment]
聞きました： https://github.com/nodeschool/international-day/issues/12

**Comment by martinheidegger** [comment]
場所見つかりました！　OIT の Vislab  グランドフロント C Tower 9階 が使えます。
すごく面白いところです。

**Comment by kamiyam** [comment]
タワーC ９F大きくて良いね

**Comment by kamiyam** [comment]
international-day、いつものNodeSchool と同じようにワークショップをする ということで良いのかな。
発表は必要？

**Comment by martinheidegger** [comment]
必要かどうかわかりませんがいつもと同じように動かない気がします。VislabはNodeJSを使ってVideowallを作っています。それのワークショッピすればどうかな〜と考えています。

**Comment by yamamanx** [comment]
5/23(土)調整中ですが、もしかすると午前中しかいけないかもしれません。午前中だけ参加させていただいてもいいですか？

**Comment by martinheidegger** [comment]
午前中だけ来るのは問題ないです！

よろしくお願いします
ハイデッガー マルティン

**Comment by yamamanx** [comment]
ありがとうございます！
