### ISSUE TITLE
国際発表会の提案などについて

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/osaka#9]
５月２３日 国際の日です！[at doorkeeper](https://nodeschool.doorkeeper.jp/events/23614) その時発表会もしたいですので発表の提案はこちらで集まって、選びたいです。今のところは発表会が1時間15分とLT30分と考えました。それを考えて 三つの２０分の発表ぐらいと三つの９分つか７分か五つか５分のLTになると思います。テーマはNodeSchoolかNodeと関係あればいいです。

**Comment by kamiyam** [comment]
テーマ、タイトルも含めてリミットはいつですか？

**Comment by martinheidegger** [comment]
テーマは Node.js と関係があるのが必要だと思います。
タイトルは４０文字いないか？ !
日にちは当日の一週間まえがいいと考えています。

**Comment by kamiyam** [comment]
こっちに書いておいた方がいいかな。
「今風なNode.jsの使いドコロ」で
